"""
Alembic Database Migrations Setup Component

Provides production-ready Alembic configuration for database schema migrations.
Use this to initialize Alembic in your project with best practices.

Usage:
    from components.backend.database.migrations import setup_alembic

    # Initialize Alembic in your project
    setup_alembic(project_root="/path/to/your/project")

    # Then use standard Alembic commands:
    # alembic revision --autogenerate -m "Add users table"
    # alembic upgrade head
"""

import os
from pathlib import Path
from typing import Optional


ALEMBIC_INI_TEMPLATE = """# Alembic Configuration File
# Auto-generated by KAPI components

[alembic]
# Path to migration scripts
script_location = migrations

# Template for generating migration scripts
file_template = %%(year)d%%(month).2d%%(day).2d_%%(hour).2d%%(hour).2d_%%(rev)s_%%(slug)s

# Timezone for revision timestamps
timezone = UTC

# Max length of characters to apply to the "slug" field
truncate_slug_length = 40

# Database URL - overridden by env variable in migrations/env.py
# DO NOT put actual credentials here - use environment variables
sqlalchemy.url = driver://user:pass@localhost/dbname

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
"""


ENV_PY_TEMPLATE = """\"\"\"
Alembic Environment Configuration

This file is run whenever an Alembic migration command is invoked.
It handles database connection and migration context setup.

SECURITY: Database credentials are loaded from environment variables only.
\"\"\"

from logging.config import fileConfig
import os
import sys
from pathlib import Path

from sqlalchemy import engine_from_config
from sqlalchemy import pool

from alembic import context

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent.parent))

# Import your database Base and models
# CUSTOMIZE THIS: Import your actual database base and all models
try:
    from app.database import Base
    # Import all models so they are registered with Base.metadata
    # Add your model imports here:
    # from app.models.user import User
    # from app.models.product import Product
except ImportError:
    # Fallback for component testing
    from sqlalchemy.ext.declarative import declarative_base
    Base = declarative_base()

# Get Alembic config object
config = context.config

# Load environment variables
# CUSTOMIZE THIS: Adjust path to your .env file if needed
try:
    from dotenv import load_dotenv
    env_path = Path(__file__).parent.parent / "config" / ".env"
    if env_path.exists():
        load_dotenv(dotenv_path=env_path)
except ImportError:
    pass  # dotenv not required

# Override database URL with environment variable
# SECURITY: Never hardcode database credentials
db_url = os.getenv("DATABASE_URL") or os.getenv("DB_URL")
if db_url:
    # Escape % characters for ConfigParser
    config.set_main_option("sqlalchemy.url", db_url.replace("%", "%%"))

# Interpret the config file for Python logging
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Set target metadata for autogenerate support
target_metadata = Base.metadata


def run_migrations_offline() -> None:
    \"\"\"Run migrations in 'offline' mode.

    This configures the context with just a URL and not an Engine.
    Calls to context.execute() will emit the SQL to a script output.
    \"\"\"
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        compare_server_default=True,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    \"\"\"Run migrations in 'online' mode.

    In this scenario we create an Engine and associate a connection with the context.
    \"\"\"
    connectable = engine_from_config(
        config.get_section(config.config_ini_section),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            compare_server_default=True,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
"""


SCRIPT_PY_MAKO_TEMPLATE = '''"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

"""
from alembic import op
import sqlalchemy as sa
${imports if imports else ""}

# revision identifiers, used by Alembic.
revision = ${repr(up_revision)}
down_revision = ${repr(down_revision)}
branch_labels = ${repr(branch_labels)}
depends_on = ${repr(depends_on)}


def upgrade() -> None:
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    ${downgrades if downgrades else "pass"}
'''


def setup_alembic(
    project_root: str,
    migrations_dir: str = "migrations",
    create_dirs: bool = True,
) -> None:
    """Initialize Alembic in your project with production-ready configuration.

    Creates:
    - alembic.ini (configuration file)
    - migrations/env.py (environment setup)
    - migrations/script.py.mako (migration template)
    - migrations/versions/ (migration scripts directory)

    Args:
        project_root: Path to your project root directory
        migrations_dir: Name of migrations directory (default: "migrations")
        create_dirs: Create directories if they don't exist (default: True)

    Example:
        from components.backend.database.migrations import setup_alembic

        # Initialize in your project
        setup_alembic("/path/to/myproject")

        # Custom migrations directory
        setup_alembic("/path/to/myproject", migrations_dir="db_migrations")

    After running this, customize migrations/env.py to import your models.
    """
    root = Path(project_root)
    migrations_path = root / migrations_dir

    if create_dirs:
        migrations_path.mkdir(parents=True, exist_ok=True)
        (migrations_path / "versions").mkdir(exist_ok=True)

    # Create alembic.ini
    alembic_ini_path = root / "alembic.ini"
    if not alembic_ini_path.exists():
        alembic_ini_path.write_text(ALEMBIC_INI_TEMPLATE)
        print(f"✅ Created {alembic_ini_path}")

    # Create env.py
    env_py_path = migrations_path / "env.py"
    if not env_py_path.exists():
        env_py_path.write_text(ENV_PY_TEMPLATE)
        print(f"✅ Created {env_py_path}")

    # Create script.py.mako
    script_mako_path = migrations_path / "script.py.mako"
    if not script_mako_path.exists():
        script_mako_path.write_text(SCRIPT_PY_MAKO_TEMPLATE)
        print(f"✅ Created {script_mako_path}")

    # Create __init__.py
    init_path = migrations_path / "__init__.py"
    if not init_path.exists():
        init_path.write_text("")
        print(f"✅ Created {init_path}")

    # Create README
    readme_path = migrations_path / "README.md"
    if not readme_path.exists():
        readme_content = f"""# Database Migrations

This directory contains Alembic database migrations.

## Setup

1. Install Alembic:
   ```bash
   pip install alembic
   ```

2. Configure environment variables:
   ```bash
   export DATABASE_URL="postgresql://user:pass@localhost:5432/dbname"
   ```

3. Customize `env.py` to import your models:
   ```python
   from app.models import User, Product  # Add all your models
   ```

## Usage

### Create a new migration
```bash
alembic revision --autogenerate -m "Add users table"
```

### Apply migrations
```bash
alembic upgrade head
```

### Rollback one migration
```bash
alembic downgrade -1
```

### View migration history
```bash
alembic history
```

### View current version
```bash
alembic current
```

## Best Practices

1. **Always review autogenerated migrations** before applying
2. **Test migrations** in development before production
3. **Backup database** before running migrations in production
4. **Never edit applied migrations** - create new ones instead
5. **Keep migrations small** - one logical change per migration

## SECURITY

- Database credentials are loaded from environment variables
- Never commit `.env` files with credentials
- Use different databases for dev/staging/production
"""
        readme_path.write_text(readme_content)
        print(f"✅ Created {readme_path}")

    print(f"\n✅ Alembic setup complete in {project_root}")
    print(f"\nNext steps:")
    print(f"1. Customize {migrations_path}/env.py to import your models")
    print(f"2. Set DATABASE_URL environment variable")
    print(f"3. Run: alembic revision --autogenerate -m 'Initial migration'")
    print(f"4. Run: alembic upgrade head")


if __name__ == "__main__":
    # Example usage
    import sys

    if len(sys.argv) < 2:
        print("Usage: python alembic_setup.py /path/to/project")
        sys.exit(1)

    setup_alembic(sys.argv[1])
