#!/usr/bin/env node

/**
 * KAPI Templates Catalog Generator
 *
 * Generates unified catalog.json manifest for all template assets:
 * - Blueprints (full applications) - from blueprints/blueprint-registry.yaml
 * - Components (reusable modules) - from components/registry.yaml
 * - Quality Baselines (best-practice checklists)
 * - Recipes (methodology guides) - from blueprints/recipe-registry.yaml
 *
 * Usage: node scripts/generate-catalog.js
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const yaml = require('js-yaml');

const TEMPLATES_ROOT = path.resolve(__dirname, '..');
const CATALOG_OUTPUT = path.join(TEMPLATES_ROOT, 'catalog.json');

// Asset type configurations
const ASSET_TYPES = {
  blueprints: {
    dir: 'blueprints',
    hasMetadata: true,
    hasBundles: true,
    pattern: /^.+\/metadata\.yaml$/,
  },
  components: {
    dir: 'components',
    hasMetadata: true,
    hasBundles: true,
    pattern: /^.+\/metadata\.yaml$/,
  },
  'quality-baselines': {
    dir: 'quality-baselines',
    hasMetadata: false,
    hasBundles: false,
    pattern: /\.md$/,
  },
  recipes: {
    dir: 'recipes',
    hasMetadata: false,
    hasBundles: false,
    pattern: /\.(yaml|md)$/,
  },
};

/**
 * Calculate SHA-256 checksum for a file
 */
function calculateSHA256(filePath) {
  const hash = crypto.createHash('sha256');
  const fileBuffer = fs.readFileSync(filePath);
  hash.update(fileBuffer);
  return hash.digest('hex');
}

/**
 * Get file size in bytes
 */
function getFileSize(filePath) {
  const stats = fs.statSync(filePath);
  return stats.size;
}

/**
 * Recursively find all files matching a pattern
 */
function findFiles(dir, pattern, results = []) {
  if (!fs.existsSync(dir)) {
    console.warn(`⚠️  Directory not found: ${dir}`);
    return results;
  }

  const entries = fs.readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      // Skip node_modules, .git, etc.
      if (!entry.name.startsWith('.') && entry.name !== 'node_modules') {
        findFiles(fullPath, pattern, results);
      }
    } else if (entry.isFile()) {
      const relativePath = path.relative(TEMPLATES_ROOT, fullPath);
      if (pattern.test(relativePath)) {
        results.push(fullPath);
      }
    }
  }

  return results;
}

/**
 * Process blueprint or component with metadata.yaml
 */
function processAssetWithMetadata(metadataPath, type) {
  try {
    const metadataContent = fs.readFileSync(metadataPath, 'utf-8');
    const metadata = yaml.load(metadataContent);

    const assetDir = path.dirname(metadataPath);
    const bundlePath = path.join(assetDir, 'bundle.tar.zst');
    const relativeBundlePath = path.relative(TEMPLATES_ROOT, bundlePath);

    const asset = {
      id: metadata.id || path.basename(assetDir),
      slug: metadata.id || path.basename(assetDir),
      name: metadata.name || 'Unnamed Asset',
      category: metadata.category || 'uncategorized',
      version: metadata.version || '1.0.0',
    };

    // Add subcategory if present
    if (metadata.subcategory) {
      asset.subcategory = metadata.subcategory;
    }

    // Add description if present
    if (metadata.description) {
      asset.description = metadata.description;
    }

    // Check if bundle exists
    if (fs.existsSync(bundlePath)) {
      asset.bundlePath = relativeBundlePath;
      asset.size = getFileSize(bundlePath);
      asset.sha256 = calculateSHA256(bundlePath);
    } else {
      // Bundle doesn't exist yet (will be generated by bundle-assets.sh)
      asset.bundlePath = relativeBundlePath;
      asset.size = 0;
      asset.sha256 = 'PENDING';
      console.warn(`⚠️  Bundle not found (will be generated): ${relativeBundlePath}`);
    }

    // Add metadata path for reference
    asset.metadataPath = path.relative(TEMPLATES_ROOT, metadataPath);

    return asset;
  } catch (error) {
    console.error(`❌ Error processing ${metadataPath}:`, error.message);
    return null;
  }
}

/**
 * Process single file asset (quality baselines, recipes)
 */
function processSingleFileAsset(filePath, type) {
  try {
    const relativePath = path.relative(TEMPLATES_ROOT, filePath);
    const fileName = path.basename(filePath, path.extname(filePath));

    const asset = {
      id: fileName,
      slug: fileName,
      name: fileName.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase()),
      filePath: relativePath,
      size: getFileSize(filePath),
      sha256: calculateSHA256(filePath),
      version: '1.0.0',
    };

    return asset;
  } catch (error) {
    console.error(`❌ Error processing ${filePath}:`, error.message);
    return null;
  }
}

/**
 * Process blueprints from blueprint-registry.yaml
 */
function processBlueprintsFromRegistry() {
  console.log('\n📦 Processing blueprints from registry...');

  const registryPath = path.join(TEMPLATES_ROOT, 'blueprints', 'blueprint-registry.yaml');

  if (!fs.existsSync(registryPath)) {
    console.warn('   ⚠️  blueprint-registry.yaml not found');
    return [];
  }

  try {
    const registryContent = fs.readFileSync(registryPath, 'utf-8');
    const registry = yaml.load(registryContent);

    if (!registry || !registry.blueprints) {
      console.warn('   ⚠️  No blueprints found in registry');
      return [];
    }

    const assets = [];

    for (const blueprint of registry.blueprints) {
      const asset = {
        id: blueprint.id,
        slug: blueprint.id,
        name: blueprint.name,
        category: blueprint.category,
        version: '1.0.0',
        bundlePath: `blueprints/${blueprint.category}/${blueprint.id}/bundle.tar.zst`,
        size: 0,  // To be calculated when bundle exists
        sha256: 'PENDING',  // To be calculated when bundle exists
      };

      if (blueprint.subcategory) {
        asset.subcategory = blueprint.subcategory;
      }

      if (blueprint.description) {
        asset.description = blueprint.description;
      }

      if (blueprint.stack) {
        asset.stack = blueprint.stack;
      }

      if (blueprint.setup_time) {
        asset.setupTime = blueprint.setup_time;
      }

      if (blueprint.difficulty) {
        asset.difficulty = blueprint.difficulty;
      }

      assets.push(asset);
    }

    console.log(`   ✅ Processed ${assets.length} blueprints from registry`);
    return assets;
  } catch (error) {
    console.error(`   ❌ Error processing blueprint registry:`, error.message);
    return [];
  }
}

/**
 * Process components from components/registry.yaml
 */
function processComponentsFromRegistry() {
  console.log('\n📦 Processing components from registry...');

  const registryPath = path.join(TEMPLATES_ROOT, 'components', 'registry.yaml');

  if (!fs.existsSync(registryPath)) {
    console.warn('   ⚠️  components/registry.yaml not found');
    return [];
  }

  try {
    const registryContent = fs.readFileSync(registryPath, 'utf-8');
    const registry = yaml.load(registryContent);

    if (!registry || !registry.components) {
      console.warn('   ⚠️  No components found in registry');
      return [];
    }

    const assets = [];

    for (const component of registry.components) {
      const asset = {
        id: component.id,
        slug: component.id,
        name: component.name,
        category: component.category,
        version: component.version || '1.0.0',
        bundlePath: `components/${component.path}/bundle.tar.zst`,
        size: 0,
        sha256: 'PENDING',
      };

      if (component.subcategory) {
        asset.subcategory = component.subcategory;
      }

      if (component.description) {
        asset.description = component.description;
      }

      assets.push(asset);
    }

    console.log(`   ✅ Processed ${assets.length} components from registry`);
    return assets;
  } catch (error) {
    console.error(`   ❌ Error processing component registry:`, error.message);
    return [];
  }
}

/**
 * Process recipes from blueprints/recipe-registry.yaml
 * Registry has multiple sections: ai_recipes, best_practices, implementation_patterns, etc.
 */
function processRecipesFromRegistry() {
  console.log('\n📦 Processing recipes from registry...');

  const registryPath = path.join(TEMPLATES_ROOT, 'blueprints', 'recipe-registry.yaml');

  if (!fs.existsSync(registryPath)) {
    console.warn('   ⚠️  recipe-registry.yaml not found');
    return [];
  }

  try {
    const registryContent = fs.readFileSync(registryPath, 'utf-8');
    const registry = yaml.load(registryContent);

    if (!registry) {
      console.warn('   ⚠️  No recipes found in registry');
      return [];
    }

    const assets = [];

    // Process all sections in the registry (ai_recipes, best_practices, etc.)
    const sections = ['ai_recipes', 'best_practices', 'implementation_patterns', 'strategic_templates', 'system_design', 'project_management'];

    for (const section of sections) {
      if (registry[section] && Array.isArray(registry[section])) {
        for (const recipe of registry[section]) {
          // Use the path from registry or construct it
          const filePath = recipe.path || `recipes/${recipe.id}.yaml`;
          const fullPath = path.join(TEMPLATES_ROOT, filePath);

          const asset = {
            id: recipe.id,
            slug: recipe.id,
            name: recipe.name,
            category: recipe.category || 'methodology',
            version: '1.0.0',
            filePath: filePath,
            size: fs.existsSync(fullPath) ? getFileSize(fullPath) : 0,
            sha256: fs.existsSync(fullPath) ? calculateSHA256(fullPath) : 'PENDING',
          };

          if (recipe.type) {
            asset.type = recipe.type;
          }

          if (recipe.description) {
            asset.description = recipe.description;
          }

          if (recipe.difficulty) {
            asset.difficulty = recipe.difficulty;
          }

          if (recipe.provides) {
            asset.provides = recipe.provides;
          }

          if (recipe.applies_to) {
            asset.appliesTo = recipe.applies_to;
          }

          if (recipe.language) {
            asset.language = recipe.language;
          }

          assets.push(asset);
        }
      }
    }

    console.log(`   ✅ Processed ${assets.length} recipes from registry`);
    return assets;
  } catch (error) {
    console.error(`   ❌ Error processing recipe registry:`, error.message);
    return [];
  }
}

/**
 * Process assets for a given type
 */
function processAssetType(type, config) {
  console.log(`\n📦 Processing ${type}...`);

  const assetDir = path.join(TEMPLATES_ROOT, config.dir);
  const assets = [];

  if (config.hasMetadata) {
    // Find all metadata.yaml files
    const metadataFiles = findFiles(assetDir, config.pattern);
    console.log(`   Found ${metadataFiles.length} ${type}`);

    for (const metadataPath of metadataFiles) {
      const asset = processAssetWithMetadata(metadataPath, type);
      if (asset) {
        assets.push(asset);
      }
    }
  } else {
    // Find all matching files
    const files = findFiles(assetDir, config.pattern);
    console.log(`   Found ${files.length} ${type}`);

    for (const filePath of files) {
      const asset = processSingleFileAsset(filePath, type);
      if (asset) {
        assets.push(asset);
      }
    }
  }

  // Sort by id
  assets.sort((a, b) => a.id.localeCompare(b.id));

  console.log(`   ✅ Processed ${assets.length} ${type}`);
  return assets;
}

/**
 * Generate catalog.json
 */
function generateCatalog() {
  console.log('🎁 KAPI Templates Catalog Generator');
  console.log('====================================\n');
  console.log(`📂 Templates root: ${TEMPLATES_ROOT}`);

  const catalog = {
    version: new Date().toISOString().split('T')[0].replace(/-/g, '.'), // YYYY.MM.DD
    generatedAt: new Date().toISOString(),
    schemaVersion: '1.0.0',
    assets: {},
  };

  // Process blueprints from registry first
  catalog.assets.blueprints = processBlueprintsFromRegistry();

  // Process components from registry
  catalog.assets.components = processComponentsFromRegistry();

  // Process recipes from registry
  catalog.assets.recipes = processRecipesFromRegistry();

  // Process quality baselines from filesystem
  catalog.assets['quality-baselines'] = processAssetType('quality-baselines', ASSET_TYPES['quality-baselines']);

  // Calculate totals
  const totals = {
    blueprints: catalog.assets.blueprints.length,
    components: catalog.assets.components.length,
    qualityBaselines: catalog.assets['quality-baselines'].length,
    recipes: catalog.assets.recipes.length,
    total: 0,
  };
  totals.total = totals.blueprints + totals.components + totals.qualityBaselines + totals.recipes;

  catalog.statistics = totals;

  // Write catalog.json
  console.log(`\n📝 Writing catalog to: ${CATALOG_OUTPUT}`);
  fs.writeFileSync(CATALOG_OUTPUT, JSON.stringify(catalog, null, 2), 'utf-8');

  console.log('\n✅ Catalog generation complete!');
  console.log('\n📊 Summary:');
  console.log(`   Blueprints: ${totals.blueprints}`);
  console.log(`   Components: ${totals.components}`);
  console.log(`   Quality Baselines: ${totals.qualityBaselines}`);
  console.log(`   Recipes: ${totals.recipes}`);
  console.log(`   ─────────────────`);
  console.log(`   Total Assets: ${totals.total}`);
  console.log(`\n   Version: ${catalog.version}`);
  console.log(`   Generated: ${catalog.generatedAt}\n`);
}

// Main execution
try {
  generateCatalog();
  process.exit(0);
} catch (error) {
  console.error('\n❌ Catalog generation failed:', error);
  console.error(error.stack);
  process.exit(1);
}
